name: Acceptance Tests

on:
#  push:
#    branches:
#      - main
#      - releases/**
  pull_request:
    branches:
      - main

jobs:
  docker:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Start backend-api containers
        run: |
          cd backend-api
          docker-compose up -d --build

      - name: Run backend-api
        run: |
          cd backend-api
          mvn verify -P acceptance-test

      - name: Stop backend-api containers
        if: always()
        run: |
          cd backend-api
          docker-compose down