name: "Test"

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: backend-api Unit testing
        run: |
          cd backend-api
          mvn clean verify

      - name: backend-api Integration testing
        run: |
          cd backend-api
          mvn clean verify -P integration-test

      - name: backend-api OWASP check
        run: |
          cd backend-api
          mvn clean verify -P owasp-dependency-check

      - name: backend-auth-user Unit testing
        run: |
          cd backend-auth-user
          mvn clean verify

      - name: backend-auth-user Integration testing
        run: |
          cd backend-auth-user
          mvn clean verify -P integration-test

      - name: backend-auth-user OWASP check
        run: |
          cd backend-auth-user
          mvn clean verify -P owasp-dependency-check